server:
  port: 8081

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/library}
    username: ${DB_UNAME:chunhou}
    password: ${DB_PW:}
  jpa:
    hibernate:
      format_sql: true
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org.springframework.cloud: DEBUG