server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: chunhou
    password:
  jpa:
    hibernate:
      format_sql: true
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect